title: "Khushali Thakkar"
logo: "https://raw.githubusercontent.com/Khushali-revaya/Khushali-revaya.github.io/master/images/Circle%20White%20(Transparent).png"
description: ""

theme: jekyll-theme-minimal
