title: "Khushali Thakkar"
logo: "https://raw.githubusercontent.com/Khushali-revaya/Khushali-revaya.github.io/master/images/Circle%20White%20(Transparent).png"
description: >
  Personal transformation starts with a conversation.  
  👉 [Book your 30-minute clarity session](https://calendly.com/d/cryz-t2v-9gk/30-minute-meeting)

theme: jekyll-theme-minimal
